# Generated by Django 4.1.4 on 2022-12-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('Salary', models.IntegerField()),
                ('Bonus', models.IntegerField()),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Role', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('DateOfJoining', models.DateField()),
            ],
        ),
    ]
